# Generated by Django 4.1.9 on 2026-03-17 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0005_coupon_order_discount_amount_order_upi_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
