# Generated by Django 4.1.9 on 2026-03-17 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0010_contactmessage_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='groceryitem',
            name='emoji',
            field=models.CharField(default='🛒', max_length=10),
        ),
    ]
