# Generated by Django 4.1.9 on 2026-03-18 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0011_groceryitem_emoji'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=300)),
                ('slide_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='image', max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='slides/')),
                ('video', models.FileField(blank=True, null=True, upload_to='slides/videos/')),
                ('video_url', models.URLField(blank=True, help_text='External video URL (YouTube embed or direct mp4)')),
                ('link', models.CharField(blank=True, help_text='URL to navigate on click (e.g. /restaurants)', max_length=300)),
                ('button_text', models.CharField(blank=True, default='Order Now', max_length=50)),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower number = shown first')),
                ('is_active', models.BooleanField(default=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Leave blank = never expires', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Hero Slide',
                'verbose_name_plural': 'Hero Slides',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
