# Generated by Django 4.1.9 on 2026-03-18 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0012_add_hero_slide'),
    ]

    operations = [
        migrations.AddField(
            model_name='heroslide',
            name='display_duration',
            field=models.PositiveIntegerField(default=4, help_text='Seconds to show this slide (image only). Min 2, Max 15.'),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='start_date',
            field=models.DateTimeField(blank=True, help_text='Show from this date (blank = always)', null=True),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text='Hide after this date (blank = never)', null=True),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='video_url',
            field=models.URLField(blank=True, help_text='External video URL (direct mp4 link)'),
        ),
    ]
