# Generated by Django 4.1.9 on 2026-03-18 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0013_heroslide_duration_startdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heroslide',
            name='display_duration',
            field=models.PositiveIntegerField(default=4, help_text='Seconds to show this slide (images only; videos use their own length)'),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='video_url',
            field=models.URLField(blank=True, help_text='External video URL (direct mp4)'),
        ),
    ]
