# Generated by Django 4.1.9 on 2026-04-07 05:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('food', '0014_heroslide_duration_startdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='heroslide',
            name='display_duration',
        ),
        migrations.RemoveField(
            model_name='heroslide',
            name='start_date',
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text='Leave blank = never expires', null=True),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='video_url',
            field=models.URLField(blank=True, help_text='External video URL (YouTube embed or direct mp4)'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('customer', 'Customer'), ('delivery', 'Delivery Boy'), ('admin', 'Admin')], default='customer', max_length=20)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
